name: Deploy App to vercel
'on':
  push:
    branches:
      - main
jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: tbvjaos510/empty-commit-action@0.0.2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          email: abdul.ghani@volteo.com
          name: Abdul Ghani
          message: trigger deployment
